name: steamfriends
environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  aws_lambda_dart_runtime:
    git: https://github.com/awslabs/aws-lambda-dart-runtime.git
  aws_sqs_api:
  aws_sns_api:
  aws_dynamodb_api:
  aws_secretsmanager_api:
  logging:
  json_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^1.10.3
  json_serializable: ^3.5.0