service: steamfinder

functions:
  steamfinder:
    handler: bootstrap
    events:
      - schedule: rate(1 minute)
        enabled: false
      - sqs:
        arn:
          Fn::GetAtt:
            - FriendQueue
            - Arn
resources:
  Resources:
    FriendQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "FriendQueue"
    FriendsHistory:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: friends-history
        AttributeDefinitions:
          - AttributeName: steamid
            AttributeType: S
        KeySchema:
          - AttributeName: steamid
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

provider:
  name: aws
  region: us-west-2
  runtime: provided
  iamRoleStatements:
    - Effect: Allow	
      Action:	
        - 'sns:Publish'	
      Resource: '*'	
    - Effect: Allow
      Action:
        - 'sqs:GetQueueAttributes'
        - 'sqs:SendMessage'
        - 'sqs:ReceiveMessage'
        - 'sqs:DeleteMessage'
        - 'sqs:DeleteMessageBatch'
        - 'sqs:GetQueueUrl'
      Resource: '*'
    - Effect: Allow
      Action:
        - 'secretsmanager:Get*'
      Resource: '*'
    - Effect: Allow
      Action:
        - 'dynamodb:*'
      Resource: '*'


package:
  exclude:
    - ./**
  include:
    - ./bootstrap